import type { FacetKey, Facets } from './types';

/**
 * Hand-written mapping from ADE tags to facets. ADE mixes genres, time of day, venue
 * size, area and event type in one tag list; anything not listed here lands in "other".
 */
const TABLE: Record<Exclude<FacetKey, 'other'>, string[]> = {
  time: ['Daytime events', 'Nighttime events', 'Morning events', 'All night long'],
  venueType: [
    'Intimate venues',
    'Mid-size venues',
    'Large venues',
    'Unique venues',
    'Warehouses',
    'Bars',
    'Rooftop venues',
    'Basements',
    'Industrial Buildlings',
    'Outdoor events',
    'Boat Parties',
    'New Arts & Culture Venues',
    'New Festival Venues',
  ],
  area: [
    'Centre',
    'West',
    'New West',
    'South',
    'South East',
    'East',
    'North',
    'NDSM',
    'Leidseplein',
    'Rembrandtplein',
    "A'DAM Toren",
  ],
  type: [
    'Club nights',
    'Live',
    'Live Performances',
    '(Live) Events',
    'Exhibitions',
    'Free Festival Events',
    'Free A&C Events',
    'Networking events',
    'Networking',
    'Music Culture',
    'Club Culture',
    'Beyond the Dancefloor',
    'Audiovisual & Immersive Arts',
    'Dance & Theatre',
    'Film & Documentaries',
    'Instore Session',
    "Showcases & Expo's",
    'Workshops, Talks & Networking',
    'Masterclasses',
    'Keynotes, Talks & Panels',
    'Radio & Livestreams',
    'Record Store Events',
    'Brunch, Bites & Beats',
    'Breakfast Club',
    'Wellbeing',
    'Sports',
    'Sports & other activities',
    'Lifestyle',
    'Meet the... Sessions',
    'Back to Back specials',
    'Get into session',
    'Indepth',
    'Specials',
    'Entertainment',
    'Culture',
    'Social impact',
    'Social Impact',
  ],
  genre: [
    'House',
    'Techno',
    'Tech-house',
    'Deep House',
    'Trance',
    'Disco',
    'Ambient & Listening',
    'Disco, Funk & Soul',
    'Electro & Wave',
    'Ambient',
    'Elektro',
    'Afro House',
    'Melodic',
    'Bass & UK',
    'Melodic House',
    'Afro, Latin & Global',
    'Progressive',
    'Deep Listening & Spatial Sound',
    'Progressive House',
    'Hard Dance',
    'Afrobeats',
    'Minimal-Techno',
    'Bass',
    'Hard Techno',
    'Hip-hop & Rap',
    'UK Garage',
    'Melodic Techno',
    'Electronica',
    'Minimal',
    'Baile Funk',
    'Disco House',
    'Contemporary',
    'Classic',
    'Soulful House',
    'Dub',
    'Alternative Electronic',
    'Funk',
    'Acid',
    'Dancehall',
    'R&B',
    'Jazz',
    'Breakbeat',
    'Drum & Bass',
    'Amapiano',
    'Big Room House',
    'Chillout',
    'Organic House',
    'Global Club',
    'Garage House',
    'Bass House',
    'Chicago House',
    'Italo Disco',
    'Indie Dance',
    'Hypnotic Techno',
    'Detroit Techno',
    'Hard Groove',
    'Latin House',
    'Boogie',
    'Jackin House',
    'Afro Latin',
    'Dub Techno',
    'Gqom',
    'Raw Techno',
    'Nu Jazz',
    'Future House',
    'Acid House',
    'Soul',
    'Hard Trance',
    'Industrial Techno',
    'Pop',
    'Ambient Techno',
    'Electro Funk',
    'Eurodance',
    'Speed Garage',
    'Jungle',
    'Hardstyle',
    'Tribal House',
    'Acid Techno',
    'Reggae',
    'Dubstep',
    'Uplifting Trance',
    'Downtempo',
    'Nu Disco',
    'Progressive Trance',
    'Italo',
    'Hardcore',
    'Trap',
    'Tech Trance',
    'Arabic Electronic',
    'Jersey Club',
    'Lo-fi House',
    'Wave',
    'Bassline',
    'Drone',
    'Micro House',
    'Balearic',
    'Neurofunk',
    'Dub Reggae',
    'Minimal Synth',
    'Grime',
    'Future Garage',
    'Peak Time Techno',
    'Happy Hardcore',
    'Leftfield',
    'IDM',
    'Beats',
  ],
};

const LOOKUP = new Map<string, Exclude<FacetKey, 'other'>>();
for (const [facet, tags] of Object.entries(TABLE) as [Exclude<FacetKey, 'other'>, string[]][]) {
  for (const t of tags) LOOKUP.set(t, facet);
}

export const FREE_TAGS = new Set(['Free Festival Events', 'Free A&C Events']);

/** Time-of-day filter labels shown in the UI. */
export const TIME_LABELS: Record<string, string> = {
  'Daytime events': 'Day',
  'Nighttime events': 'Night',
  'Morning events': 'Morning',
  'All night long': 'All night',
};

export const FACET_LABELS: Record<FacetKey, string> = {
  genre: 'Genre',
  time: 'Time of day',
  venueType: 'Venue type',
  area: 'Area',
  type: 'Event type',
  other: 'Other',
};

export function facetOf(tag: string): FacetKey {
  return LOOKUP.get(tag) ?? 'other';
}

export function splitFacets(tags: string[]): Facets {
  const out: Facets = { genre: [], time: [], venueType: [], area: [], type: [], other: [] };
  for (const t of tags) {
    const f = facetOf(t);
    if (!out[f].includes(t)) out[f].push(t);
  }
  return out;
}
